### ISSUE TITLE
Documentation 404

### ISSUE THREAD

**Issue by avivbueno** [rmuif/docs#1]
Hey,

I'm trying to access the documentation website but 404 on https://docs.rmuif.com/
looks like CD issue after last changes. Sorry if interrupting during a big change. Please keep the docs on the website up for developers. before it got down some things were unclear in authorization doc page because tools are not currently in the master repo.

**Comment by phoqe** [comment]
Hmm, I got the impression that it was working the last time I looked at it. I will investigate it further. Thank you for noticing and creating an issue though! :)

**Comment by phoqe** [comment]
@avivbueno It should work now, apologies for any inconvenience. Reopen if there's a problem. Have a good night.

**Comment by MDB22** [comment]
@phoqe I'm now getting a 404 error for https://docs.rmuif.com/

**Comment by phoqe** [comment]
> @phoqe I'm now getting a 404 error for https://docs.rmuif.com/

Oh, I will take a look!

**Comment by phoqe** [comment]
Should be fixed now @MDB22

**Comment by MDB22** [comment]
Thank you very much for the quick fix!
